inherit_from: ../../../.rubocop.yml

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  UseHashRocketsWithSymbolValues: true
  SupportedStyles:
    - ruby19
    - ruby19_no_mixed_keys
    - hash_rockets
